config/routes.rb
ShoeSales::Application.routes.draw do
  get "/register", :to => 'users#new'
  post "/register", :to => 'users#create'

  get "/login", :to => 'sessions#new'
  post "/login", :to => 'sessions#create'
  delete "/logout", :to => 'sessions#destroy'

  resources :users, :only => [:new, :create, :show]
  post "/users/:id", :to => 'users#show'	#post for product 'edit' function

  resources :products, :only => [:index, :create, :update, :destroy]

  root :to => 'sessions#new'
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :seller, :class_name => "User"
	belongs_to :buyer, :class_name => "User"

	validates :model,	:brand,	:amount,		:presence	=> true

	def name
		"#{self.model} #{self.brand}"
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	CRAZY_EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

	has_many :products, :foreign_key => "seller_id"
	has_many :purchases, :class_name => "Product", :foreign_key => "buyer_id"

	validates :first_name, :last_name,
							:presence		=> true,
							:length			=> { :within => 1..50 }
	validates :email,
							:presence	=> true,
							:format => {
								:with	=> CRAZY_EMAIL_REGEX,
								:message	=> "Incorrect email format." },
							:uniqueness	=> {
								:case_sensitive => false }
	validates :password,
							:presence	=> true,
							:length		=> { :within => 6..40 }

	before_save { self.email = email.downcase } 
	has_secure_password

	def name
		"#{self.first_name} #{self.last_name}"
	end

	def sales
		self.products.where.not(:buyer_id => nil)
	end

	def available
		self.products.where(:buyer_id => nil)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
		@products = Product.includes(:seller).where(:buyer_id => nil)
	end

	def create
		@product = current_user.products.new(product_params)
		if @product.save
		redirect_to user_url(current_user), :notice => "#{@product.name}s listed!"
		else
		  redirect_to user_url(current_user), :alert => "Product not listed!"
		end
	end

	def update
		@product = Product.find(params[:id])

		if params[:product][:action] == "purchase"
			@product.buyer_id = current_user
			if @product.save
				redirect_to user_url(current_user),
					:notice => "#{@product.name} purchased!"
			else
				redirect_to user_url(current_user),
					:alert => "Unable to complete purchase of #{@product.name}."
			end
		else	#we're just updating product information
			@product.update(product_params)
			if @product.save
				redirect_to user_url(current_user),
					:notice => "#{@product.name} updated."
			else
				redirect_to user_url(current_user),
					:alert => "Unable to update this product."
			end
		end
	end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy
		redirect_to user_url(current_user)
	end

	private
	def product_params
		params.require(:product).permit(:model, :brand, :amount)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by_email(params[:session][:email])
		if user == false || user.nil?
			redirect_to login_url,
			:flash => { :alert => 'No user exists with that email' }
		else
			user = user.try(:authenticate, params[:session][:password])
			if user == false || user.nil?
				redirect_to login_url,
				:flash => { :alert => 'Incorrect password.' }
			else
				sign_in user
				redirect_to user_url(user)
			end
		end
	end

	def destroy
		sign_out
		redirect_to login_url
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			sign_in @user
			redirect_to user_url(@user), :notice => "Welome to the app, #{@user.name}!"
		else
			render :new
		end
	end

	def show
		@user = User.find(params[:id])
		@available_products = @user.available
		if current_user == @user
			@product = Product.find(params[:product][:id]) if params[:product]
			@product ||= Product.new
			@sales = @user.sales
			@purchases = @user.purchases
		end
	end

	private
	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		session[:user_id] = user.id
		self.current_user = user
	end

	# setter method
	def current_user=(user)
		@current_user = user
	end

	# getter method
	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def signed_in?
		!current_user.nil?
	end

	def sign_out
		session[:user_id] = nil
		self.current_user = nil
	end

	def current_user?(user)
		user == current_user 
	end

	def deny_access
		redirect_to login_path, :alert => "Please sign in to access that page."
	end

	def deny_access_to_restricted_info
	  #No matter what the bad user is doing, redirect to their dashboard:
		redirect_to user_url(current_user),
			:alert => "You do not have the authority to access that page!"
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShoeSales</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %></title>
  <%= stylesheet_link_tag    "sessions", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "sessions", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:notice] %>
	<p class="alert alert-info">><%= flash[:notice] %></p>
<% elsif flash[:alert] %>
	<p class="alert alert-danger"><%= flash[:alert] %></p>
<% end %>
<%= yield %>

</body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %></title>
  <%= stylesheet_link_tag    "users", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "users", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:notice] %>
	<p class="alert alert-info"><%= flash[:notice] %></p>
<% elsif flash[:alert] %>
	<p class="alert alert-danger"><%= flash[:alert] %></p>
<% end %>
<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="<%= user_url(current_user) %>">Welcome, <%= current_user.first_name %></a>
  </div>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Log Out", logout_url, :method => :delete %></li>
    </ul>
  </div>
</nav>
<div class="clearfix"></div>

<div class="table-responsive">
  <table class="table table-striped table-condensed margin10">
    <caption class="text-left">Available Products:</caption>
    <thead>
      <tr>
        <th>Product</th>
        <th>Seller</th>
        <th>Date Posted</th>
        <th>Amount</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.seller.name %></td>
        <td><%= product.created_at.strftime("%m/%d/%Y") %></td>
        <td><%= product.amount.to_digits %></td>
        <td><%= link_to "Buy", product_url(product) %></td>
      </tr>
      <% end %><!-- end @sales.each -->
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<% content_for :title do %>
	Registration
<% end %>

<div id="register_wrapper" class="margin10">
	<h2>Register</h2>
	<%= simple_form_for @user,	:url => register_url do |f| %>
			<%= f.input :first_name, :label => false,
												:placeholder => 'First Name' %>
			<%= f.input :last_name, :label => false,
												:placeholder => 'Last Name' %>
			<%= f.input :email, :label => false,
												:placeholder => 'Email Address' %>
			<%= f.input :password, :label => false,
												:placeholder => 'Enter a password' %>
			<%= f.input :password_confirmation, :label => false,
												:placeholder => 'Confirm password' %>
			<%= f.submit 'Register User!', :class => "btn btn-primary" %>
	<% end %>
	<p class="text-left top_margin10 no_bottom_spacing">Already Registered?</p>
	<p class="text-left"><%= link_to "Login", login_url %> here!</p>
</div>

app/views/users/show.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="<%= user_url(current_user) %>">Welcome, <%= current_user.first_name %></a>
  </div>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Available Shoes", products_url %></li>
     <!--  <li class="divider-vertical"></li> -->
      <li><%= link_to "Log Out", logout_url, :method => :delete %></li>
    </ul>
  </div>
</nav>
<div class="clearfix"></div>

<% if current_user == @user %>
	<div id="product_form">
		<h4 class="text-left">Sell Product</h4>

		<%= simple_form_for @product,
							:html => { 
                :class => "border-silver margin10 padding10 col-xs-3"
              } do |f| %>
			<%= f.input :brand %>
			<%= f.input :model %>
			<%= f.input :amount %>
      <% if @product.id.nil? %>
		    <%= f.submit 'Sell', :class => "btn btn-primary" %>
      <% else %>
        <%= f.submit 'Update', :class => "btn btn-primary" %>
      <% end %>
		<% end %>
	</div>

	<!-- Unsold Product table -->
  <div class="table-responsive">
  	<table class="table table-striped table-condensed margin10">
  		<caption class="text-left">Products for Sale:</caption>
  		<thead>
  			<tr>
          <th>Product</th>
          <th>Date Posted</th>
          <th>Amount</th>
          <th>Action</th>
  			</tr>
  		</thead>
      <tbody>
        <% @available_products.each do |product| %>
          <tr>
            <td><%= product.name %></td>
            <td><%= product.created_at.strftime("%m/%d/%Y") %></td>
            <td><%= product.amount.to_digits %></td>
            <td>
            	<%= link_to "Remove", product_url(product),
            			:confirm => "Are you sure you want to remove #{product.name}?",
            			:method => :delete %>
              <%= form_for product,
                  :method => :post,
                  :url => user_url(current_user)  do |f| %>
                <%= f.hidden_field :id, :value => product.id %>
                <%= f.submit 'Edit', :class => "btn btn-link" %>
              <% end %>
            </td>
          </tr>
        <% end %><!-- end @sales.each -->
      </tbody>
    </table>
  </div>

  <div class="table-responsive">
	<!-- Sold Product table -->
  	<table class="table table-striped table-condensed margin10">
  		<caption class="text-left">Sales</caption>
  		<thead>
  			<tr>
          <th>Product</th>
          <th>Date Sold</th>
          <th>Buyer</th>
          <th>Amount</th>
  			</tr>
  		</thead>
      <tbody>
        <% @sales.each do |sale| %>
          <tr>
            <td><%= sale.name %></td>
            <td><%= sale.updated_at.strftime("%m/%d/%Y") %></td>
            <td><%= link_to "#{sale.buyer.name}", user_url(sale.buyer) %></td>
            <td><%= sale.amount.to_digits %></td>
          </tr>
        <% end %><!-- end @sales.each -->
      </tbody>
    </table>
  </div>

  <div class="table-responsive">
	<!-- Purchased Product table -->
  	<table class="table table-striped table-condensed margin10">
  		<caption class="text-left">Purchases</caption>
  		<thead>
  			<tr>
          <th>Product</th>
          <th>Date Bought</th>
          <th>Seller</th>
          <th>Amount</th>
  			</tr>
  		</thead>
      <tbody>
        <% @purchases.each do |purchase| %>
          <tr>
            <td><%= purchase.name %></td>
            <td><%= purchase.updated_at.strftime("%m/%d/%Y") %></td>
            <td><%= link_to "#{purchase.seller.name}", user_url(purchase.seller)  %></td>
            <td><%= purchase.amount.to_digits %></td>
          </tr>
        <% end %><!-- end @purchases.each -->
      </tbody>
    </table>
  </div>
<% else %>
	<!-- products for sale by @user -->
  <div class="table-responsive">
  	<table class="table table-striped table-condensed margin10">
  		<caption class="text-left"><%= @user.name %>'s Products</caption>
  		<thead>
  			<tr>
          <th>Product</th>
          <th>Date Posted</th>
          <th>Amount</th>
          <th>Action</th>
  			</tr>
  		</thead>
      <tbody>
        <% @available_products.each do |product| %>
          <tr>
            <td><%= product.name %></td>
            <td><%= product.created_at.strftime("%m/%d/%Y") %></td>
            <td><%= product.amount.to_digits %></td>
            <td>
            	<%= form_for product,
            							:url => product_url(product)  do |f| %>
            		<%= f.submit 'Buy', :class => "btn btn-link" %>
            	<% end %>
            </td>
          </tr>
        <% end %><!-- end @products.each -->
      </tbody>
    </table>
  </div>
<% end %>